#!/usr/bin/env node
/**
 * Sherpa — interactive env-var setup.
 *
 * Run: npm run setup
 *
 * Prompts for the three Supabase values + site URL, validates them
 * roughly, writes .env.local, and prints the exact Vercel env vars
 * to copy into the Vercel dashboard.
 *
 * Safe to re-run: existing values are shown as defaults.
 */

import * as readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const envPath = join(here, "..", ".env.local");

// ---------- helpers ----------

function loadExisting() {
  if (!existsSync(envPath)) return {};
  const out = {};
  for (const raw of readFileSync(envPath, "utf-8").split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    out[line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
  }
  return out;
}

const RED = "\x1b[31m";
const GREEN = "\x1b[32m";
const DIM = "\x1b[2m";
const BOLD = "\x1b[1m";
const RESET = "\x1b[0m";
const BLUE = "\x1b[34m";

const isSupabaseUrl = (s) =>
  /^https:\/\/[a-z0-9]+\.supabase\.co\/?$/.test(s.trim());
const isJwt = (s) =>
  /^eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(s.trim());
const isUrl = (s) => {
  try {
    new URL(s);
    return true;
  } catch {
    return false;
  }
};

async function ask(rl, label, current, validate, hint) {
  while (true) {
    const shown = current ? `${DIM}[${current.slice(0, 40)}${current.length > 40 ? "…" : ""}]${RESET} ` : "";
    const answerRaw = await rl.question(`  ${BOLD}${label}${RESET}\n  ${shown}${hint ? DIM + hint + RESET + " " : ""}> `);
    const answer = (answerRaw || current || "").trim();
    if (!answer) {
      console.log(`  ${RED}Required.${RESET}`);
      continue;
    }
    if (validate) {
      const err = validate(answer);
      if (err) {
        console.log(`  ${RED}${err}${RESET}`);
        continue;
      }
    }
    return answer;
  }
}

// ---------- main ----------

const existing = loadExisting();

console.log(`${BLUE}${BOLD}\nSherpa env-var setup${RESET}`);
console.log(DIM + "Press Enter to keep the existing value shown in [brackets].\n" + RESET);
console.log(`${DIM}Get your Supabase values at: Settings → API in your Supabase dashboard.${RESET}\n`);

const rl = readline.createInterface({ input, output });

try {
  const supabaseUrl = await ask(
    rl,
    "Supabase Project URL",
    existing.NEXT_PUBLIC_SUPABASE_URL,
    (s) => (isSupabaseUrl(s) ? null : "Must look like https://yourref.supabase.co"),
    "(public, safe in browser)",
  );

  const anonKey = await ask(
    rl,
    "Supabase anon (public) key",
    existing.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    (s) => (isJwt(s) ? null : "Must be a JWT (three base64 segments separated by dots)"),
    "(public, safe in browser)",
  );

  const serviceRoleKey = await ask(
    rl,
    "Supabase service_role key",
    existing.SUPABASE_SERVICE_ROLE_KEY,
    (s) => (isJwt(s) ? null : "Must be a JWT (three base64 segments separated by dots)"),
    "(SECRET — server-only, never expose to browser)",
  );

  const siteUrl = await ask(
    rl,
    "Public site URL",
    existing.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
    (s) => (isUrl(s) ? null : "Must be a valid URL like http://localhost:3000"),
    "(use http://localhost:3000 for dev; your Vercel URL for prod)",
  );

  // Sanity check: anon and service-role MUST be different.
  if (anonKey === serviceRoleKey) {
    console.log(
      `\n${RED}✗ The anon key and service_role key are identical.${RESET} That can't be right —`,
    );
    console.log("  go back to Supabase Settings → API and double-check you grabbed both.");
    process.exit(1);
  }

  // Write .env.local
  const content = [
    "# Sherpa env vars — generated by `npm run setup`",
    "# Safe to edit by hand. .env.local is git-ignored.",
    "",
    "# --- Public (sent to the browser) ---",
    `NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}`,
    `NEXT_PUBLIC_SITE_URL=${siteUrl}`,
    "",
    "# --- Server-only (DO NOT expose to browser) ---",
    `SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}`,
    "",
  ].join("\n");

  writeFileSync(envPath, content, { mode: 0o600 });
  console.log(`\n${GREEN}✓ Wrote .env.local${RESET}`);
  console.log(`  ${DIM}File mode: 0600 (owner-only)${RESET}\n`);

  // Print the Vercel env vars to copy
  console.log(`${BOLD}${BLUE}Add these to Vercel${RESET} ${DIM}(Project → Settings → Environment Variables)${RESET}\n`);

  const vercelVars = [
    { name: "NEXT_PUBLIC_SUPABASE_URL", value: supabaseUrl, secret: false },
    { name: "NEXT_PUBLIC_SUPABASE_ANON_KEY", value: anonKey, secret: false },
    { name: "NEXT_PUBLIC_SITE_URL", value: siteUrl, secret: false, note: "Update to your Vercel URL after first deploy" },
    { name: "SUPABASE_SERVICE_ROLE_KEY", value: serviceRoleKey, secret: true },
  ];

  for (const v of vercelVars) {
    const flag = v.secret ? `  ${RED}[SECRET]${RESET}` : `  ${DIM}[PUBLIC]${RESET}`;
    console.log(`${flag} ${BOLD}${v.name}${RESET}`);
    console.log(`           ${v.value}`);
    if (v.note) console.log(`           ${DIM}note: ${v.note}${RESET}`);
    console.log();
  }

  console.log(`${BOLD}Next steps:${RESET}`);
  console.log("  1. Run `npm run dev` and visit http://localhost:3000");
  console.log("  2. Sign up. Check your email for the magic link.");
  console.log("  3. Set your master passphrase + save the recovery code");
  console.log("  4. Create your first project and add a credential\n");
  console.log(
    `${DIM}If signup fails, verify Supabase Auth → URL Configuration includes\n` +
      `${siteUrl} in BOTH the Site URL field and the Redirect URLs list.${RESET}\n`,
  );
} finally {
  rl.close();
}
